name: build

on:
  pull_request:
  push:

jobs:
  check-pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.CHECKOUT_BRANCH }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files --verbose
